# fly.toml app configuration file generated for helicone-grafana on 2025-06-30T10:32:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helicone-grafana'
primary_region = 'sjc'

[build]
  image = 'grafana/grafana:12.0.1'

[[mounts]]
  source = 'grafana_storage_1'
  destination = '/var/lib/grafana'
  initial_size = '10gb'

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '20s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'

[[files]]
  guest_path = '/etc/grafana/provisioning/datasources/datasources.yaml'
  local_path = './datasources-production.yaml'

[[files]]
  guest_path = '/etc/grafana/grafana.ini'
  local_path = './config-production.yaml'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 3010
  path = '/metrics'
