{{- if .Values.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "helicone.name" . }}
  namespace: {{ .Values.argocd.namespace | default "argocd" }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project | default "default" }}
  source:
    repoURL: {{ .Values.argocd.source.repoURL | required "ArgoCD source repoURL is required" }}
    targetRevision: {{ .Values.argocd.source.targetRevision | default "HEAD" }}
    path: {{ .Values.argocd.source.path | default "helicone" }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.argocd.source.helm.parameters }}
      parameters:
        {{- range .Values.argocd.source.helm.parameters }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      {{- end }}
  destination:
    server: {{ .Values.argocd.destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.argocd.destination.namespace | default .Release.Namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.syncPolicy.automated.prune | default true }}
      selfHeal: {{ .Values.argocd.syncPolicy.automated.selfHeal | default true }}
      allowEmpty: {{ .Values.argocd.syncPolicy.automated.allowEmpty | default false }}
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: {{ .Values.argocd.syncPolicy.retry.limit | default 5 }}
      backoff:
        duration: {{ .Values.argocd.syncPolicy.retry.backoff.duration | default "5s" }}
        factor: {{ .Values.argocd.syncPolicy.retry.backoff.factor | default 2 }}
        maxDuration: {{ .Values.argocd.syncPolicy.retry.backoff.maxDuration | default "3m" }}
  revisionHistoryLimit: {{ .Values.argocd.revisionHistoryLimit | default 3 }}
{{- end }} 