helicone:
  aiGateway:
    enabled: true
    image:
      repository: helicone/ai-gateway
      pullPolicy: IfNotPresent
      tag: "sha-765b2b1"
    replicaCount: 2

    # Rolling Update Deployment Strategy
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

    # Progress deadline for deployments (in seconds)
    progressDeadlineSeconds: 600

    service:
      annotations: {}
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
      className: "nginx"
      annotations: {}
      hosts:
        - host: helicone.ai/ai-gateway
          paths:
            - path: /
              pathType: Prefix
      tls: []
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi

    # Health Probes Configuration
    livenessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1

    startupProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    extraEnvVars:
      - name: AI_GATEWAY__SERVER__ADDRESS
        value: "0.0.0.0"
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: helicone-ai-gateway-secrets
            key: openai_api_key
      # Only required if deployment target == cloud
      # - name: AI_GATEWAY__MINIO__ACCESS_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_user
      # - name: AI_GATEWAY__MINIO__SECRET_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_password
    config:
      routers:
        default:
          load-balance:
            chat:
              strategy: latency
              targets:
                - openai
                - anthropic
      providers:
        ollama:
          base-url: "http://ollama:11434"
        bedrock:
          base-url: "https://bedrock.us-east-1.amazonaws.com"
      helicone:
        authentication: true

    secrets:
      # Set these values using kubectl create secret or your preferred secrets management
      # kubectl create secret generic helicone-ai-gateway-secrets \
      #   --from-literal=proxy_helicone_api_key="your-key-here" \
      #   --from-literal=openai_api_key="your-key-here" \
      #   --from-literal=anthropic_api_key="your-key-here" \
      #   --from-literal=gemini_api_key="your-key-here" \
      #   --from-literal=helicone_api_key="your-key-here"
      aiGatewayOpenaiApiKey: ""
      aiGatewayAnthropicApiKey: ""
      aiGatewayGeminiApiKey: ""
      aiGatewayHeliconeApiKey: ""
